/*
 * Mood and Food Logging App
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(clippy::to_string_trait_impl)]
#![allow(clippy::new_without_default)]

pub mod moo_foo_log_get_dto;
pub use self::moo_foo_log_get_dto::MooFooLogGetDto;
pub mod moo_foo_log_post_dto;
pub use self::moo_foo_log_post_dto::MooFooLogPostDto;
