/**
 * Alarmservice Demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class MooFooLogPostDto {
    'timestamp': string;
    'mood': string;
    'food1'?: string;
    'food1Time'?: string;
    'food2'?: string;
    'food2Time'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "string"
        },
        {
            "name": "mood",
            "baseName": "mood",
            "type": "string"
        },
        {
            "name": "food1",
            "baseName": "food1",
            "type": "string"
        },
        {
            "name": "food1Time",
            "baseName": "food1Time",
            "type": "string"
        },
        {
            "name": "food2",
            "baseName": "food2",
            "type": "string"
        },
        {
            "name": "food2Time",
            "baseName": "food2Time",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MooFooLogPostDto.attributeTypeMap;
    }
}

