server:
  port: 9011

logging:
  levels:
    - hyper=info
    - sqlx=warn
    - tower=info
    - moofoo-backend=debug

postgres:
  host: "localhost"
  port: 20011
  user: "demo"
  password: "demo"
  database: "moofoolog_postgres"
