server:
  port: 9011

logging:
  levels:
    - hyper=info
    - sqlx=warn
    - tower=info
    - moofoolog=debug

postgres:
  host: "postgres"
  port: 5432
  user: "demo"
  password: "demo"
  database: "moofoolog_postgres"
