openapi: "3.0.0"
info:
  version: 1.0.0
  title: Alarmservice Demo

paths:
  /hello:
    get:
      parameters:
        - in: query
          name: name
          required: false
          schema:
            type: string
            example: World
      summary: A healthcheck endpoint
      responses:
        "200":
          description: OK

  /moofoolog:
    get:
      summary: query all
      responses:
        "200":
          description: OK

    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MooFooLogPost"
      responses:
        "201":
          description: Created

components:
  schemas:
    MooFooLogPost:
      type: object
      properties:
        # userName:       --> now comes via auth token in backend
        #   type: string
        mood:
          type: string
        food1:
          type: string
        food1Time:
          type: string
        food2:
          type: string
        food2Time:
          type: string

      required:
        - timestamp
        # - userName
        - mood

    MooFooLogGet:
      description: "GET"
      allOf:
        - $ref: "#/components/schemas/MooFooLogPost"
        - type: object
          properties:
            timestamp:
              type: string
              format: date-time
            userName:
              type: string
          required:
            - timestamp
            - userName
